version: "3.8"

services:
  backend:
    container_name: vrg_backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app # Asegúrate de que los archivos de backend estén disponibles en el contenedor

  db:
    image: postgres:15
    container_name: vrg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roulette
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data:
